# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PassGeneratorlowerandupper.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 582)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #808080, stop:1 #3fada8);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.generate_btn = QtWidgets.QPushButton(self.centralwidget)
        self.generate_btn.setGeometry(QtCore.QRect(320, 400, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Yekan")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.generate_btn.setFont(font)
        self.generate_btn.setStyleSheet("QPushButton{\n"
"background-color: #00416A;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:20px;\n"
"\n"
"}")
        self.generate_btn.setObjectName("generate_btn")
        self.lower = QtWidgets.QCheckBox(self.centralwidget)
        self.lower.setGeometry(QtCore.QRect(90, 110, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lower.setFont(font)
        self.lower.setWhatsThis("")
        self.lower.setAutoFillBackground(False)
        self.lower.setStyleSheet("background-color: none;\n"
"color:rgb(0, 0, 0);\n"
"")
        self.lower.setTristate(False)
        self.lower.setObjectName("lower")
        self.upper = QtWidgets.QCheckBox(self.centralwidget)
        self.upper.setGeometry(QtCore.QRect(90, 150, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.upper.setFont(font)
        self.upper.setStyleSheet("background-color: none;\n"
"color:rgb(0, 0, 0);\n"
"")
        self.upper.setObjectName("upper")
        self.pushButtonexit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonexit.setGeometry(QtCore.QRect(730, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(11)
        self.pushButtonexit.setFont(font)
        self.pushButtonexit.setStyleSheet("QPushButton{\n"
"    background-color: none;\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"}\n"
"")
        self.pushButtonexit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../R (6).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonexit.setIcon(icon)
        self.pushButtonexit.setIconSize(QtCore.QSize(31, 31))
        self.pushButtonexit.setObjectName("pushButtonexit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(560, 120, 191, 111))
        self.label.setStyleSheet("background-color: none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../R (8).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 360, 301, 221))
        self.label_2.setStyleSheet("background-color: none;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../R (7).png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pass_length = QtWidgets.QTextEdit(self.centralwidget)
        self.pass_length.setGeometry(QtCore.QRect(340, 260, 131, 41))
        self.pass_length.setStyleSheet("background-color: #E4E5E6;\n"
"border-radius:15px;")
        self.pass_length.setObjectName("pass_length")
        self.generated_pass = QtWidgets.QTextEdit(self.centralwidget)
        self.generated_pass.setGeometry(QtCore.QRect(270, 310, 281, 71))
        self.generated_pass.setStyleSheet("background-color: #E4E5E6;\n"
"border-radius:15px;")
        self.generated_pass.setObjectName("generated_pass")
        self.label_length = QtWidgets.QLabel(self.centralwidget)
        self.label_length.setGeometry(QtCore.QRect(280, 270, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_length.setFont(font)
        self.label_length.setStyleSheet("background-color:none;")
        self.label_length.setObjectName("label_length")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(640, 430, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setGeometry(QtCore.QRect(640, 490, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(11)
        self.clear_btn.setFont(font)
        self.clear_btn.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.clear_btn.setObjectName("clear_btn")
        self.check_syms = QtWidgets.QCheckBox(self.centralwidget)
        self.check_syms.setGeometry(QtCore.QRect(90, 190, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_syms.setFont(font)
        self.check_syms.setStyleSheet("background-color: none;\n"
"color:rgb(0, 0, 0);\n"
"")
        self.check_syms.setObjectName("check_syms")
        self.check_num = QtWidgets.QCheckBox(self.centralwidget)
        self.check_num.setGeometry(QtCore.QRect(90, 70, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_num.setFont(font)
        self.check_num.setStyleSheet("background-color: none;\n"
"color:rgb(0, 0, 0);\n"
"")
        self.check_num.setObjectName("check_num")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButtonexit.clicked.connect(MainWindow.close)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.generate_btn.setText(_translate("MainWindow", "GENERATE"))
        self.lower.setText(_translate("MainWindow", "LowerCase"))
        self.upper.setText(_translate("MainWindow", "UpperCase"))
        self.label_length.setText(_translate("MainWindow", "Length:"))
        self.pushButton.setText(_translate("MainWindow", "COPY"))
        self.clear_btn.setText(_translate("MainWindow", "CLEAR"))
        self.check_syms.setText(_translate("MainWindow", "Symbols"))
        self.check_num.setText(_translate("MainWindow", "Numbers"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
